---
driver:
  name: docker
  socket: unix:///var/run/docker.sock
 
  privileged: <% if ENV['PRIVILEGED'] %><%= ENV['PRIVILEGED'] %><% else %>false<% end %>
  use_sudo: false
  hostname: "simple"
  username: root

provisioner:
  name: ansible_push
  chef_bootstrap_url: nil
  ansible_config: "test/ansible.cfg"
  idempotency_test: false
  diff: true
  verbose: 'vv'

platforms:
  - name: manageiq-gaprindashvili-2
    driver:
      run_command: /usr/sbin/init
      run_options: --tty -e 'container=docker'
      image: abraverm/manageiq:gaprindashvili-2
      platform: centos
      publish_all: true
      provision_command:
        - rm -rf /etc/fstab
        - sed -i 's/UsePAM yes/UsePAM no/' /etc/ssh/sshd_config
        - systemctl enable sshd
        - /usr/bin/systemctl disable appliance-initialize evmserverd evminit evm-watchdog miqvmstat miqtop
        - rm -rf /var/www/miq/vmdb/certs/*
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      forward:
        - 443
        - 5432
      run_options:
        tmpfs:
          - /var/opt/rh/rh-postgresql95/lib/pgsql

verifier:
  name: inspec

suites:
  - name: database-present
    provisioner:
      playbook: "test/integration/database/ansible/present.yml"
    verifier:
      inspec_tests:
        - path: test/integration/database
      controls:
        - database-01

  - name: database-absent
    provisioner:
      playbook: "test/integration/database/ansible/absent.yml"
    verifier:
      inspec_tests:
        - path: test/integration/database
      controls:
        - database-02

  - name: database-backup
    provisioner:
      playbook: "test/integration/database/ansible/backup.yml"
    verifier:
      inspec_tests:
        - path: test/integration/database
      controls:
        - database-03

  - name: database-restore
    provisioner:
      playbook: "test/integration/database/ansible/restore.yml"
    verifier:
      inspec_tests:
        - path: test/integration/database
      controls:
        - database-05

  - name: database-reset
    provisioner:
      playbook: "test/integration/database/ansible/reset.yml"
    verifier:
      inspec_tests:
        - path: test/integration/database
      controls:
        - database-04

  - name: database-standalone
    provisioner:
      playbook: "test/integration/database/ansible/standalone.yml"
    verifier:
      inspec_tests:
        - path: test/integration/database
      controls:
        - database-01

  - name: database-replicate
    driver:
      instance_name: database-primary
    provisioner:
      playbook: "test/integration/database/ansible/replicate.yml"
    verifier:
      inspec_tests:
        - path: test/integration/database
      controls:
        - database-01
        - database-06

  - name: database-failover
    driver:
      instance_name: database-standby
      links: database-primary:database-primary
    provisioner:
      playbook: "test/integration/database/ansible/failover.yml"
    verifier:
      inspec_tests:
        - path: test/integration/database
      controls:
        - database-06

  - name: database-external
    driver:
      links:
        - database-primary:database-primary
        - database-standby:database-standby
    provisioner:
      playbook: "test/integration/database/ansible/external.yml"
    verifier:
      inspec_tests:
        - path: test/integration/database
      controls:
        - database-01


  - name: key-create
    provisioner:
      playbook: "test/integration/key/ansible/create.yml"
    verifier:
      inspec_tests:
        - path: test/integration/key
      controls:
        - key-01

  - name: key-master
    driver:
      instance_name: key-master
    provisioner:
      playbook: "test/integration/key/ansible/master.yml"
    verifier:
      inspec_tests:
        - path: test/integration/key
      controls:
        - key-01

  - name: key-slave
    driver:
      instance_name: key-slave
      links: key-master:key-master
    provisioner:
      playbook: "test/integration/key/ansible/slave.yml"
    verifier:
      inspec_tests:
        - path: test/integration/key
      controls:
        - key-01

  - name: key-fail-credentials
    driver:
      links: key-master:key-master
    provisioner:
      playbook: "test/integration/key/ansible/slave-fail-credentials.yml"
